for (let j=0; j < streamlist.length; j++){function a(){
if (streamlist[j].player == '0'){window["stlink_" + j] = '<iframe src="'+'https://animachtk.github.io/player/playerjs.html?file='+streamlist[j].src + '&autoplay=1' + '" frameborder="0" allowfullscreen="true"></iframe>';}
if (streamlist[j].player == '1'){window["stlink_" + j] = '<iframe src="'+'https://goodgame.ru/player?' + streamlist[j].src + '#autoplay'+'" frameborder="0" allowfullscreen="true"></iframe>';}
if (streamlist[j].player == 'yt'){window["stlink_" + j] = '<iframe width="100%" src="'+'https://www.youtube.com/embed/' + streamlist[j].src + '?autoplay=1" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';}
if (streamlist[j].player == 'tw'){window["stlink_" + j] = 
'<iframe src="https://player.twitch.tv?channel=' + streamlist[j].src + '&parent='+location.host+'&amp;migration=true&amp;" allowfullscreen="" scrolling="no" frameborder="0" allow="autoplay; fullscreen" title="Twitch" sandbox="allow-modals allow-scripts allow-same-origin allow-popups allow-popups-to-escape-sandbox"></iframe>';}
$(`<li class="rectangle-item"><a><span class="list-item">${streamlist[j].name}</span></a></li>`).appendTo(".rectangle").on("click", function(){$('#currenttitle').remove();$('.video').remove();window["stream_" + j]();$('.rectangle-item').removeClass('active');$(this).addClass('active');});window["stream_" + j] = function(){$(`<div id="currenttitle">${streamlist[j].name}</div><div class="video">${window["stlink_" + j]}</div>`).appendTo('#videowrap');}}a();}
//style
$(`<style>#sl-btn{display: none}.rectangle{counter-reset: li; list-style: none; font: 14px "Trebuchet MS", "Lucida Sans";padding: 0;text-shadow: 0 1px 0 rgba(255,255,255,.5);}.rectangle a{position: relative;display: block;padding: .4em .4em .4em .8em;margin: .5em 0 .5em 2.5em;color: #fff;text-decoration: none;transition: all .3s ease-out;}.rectangle a:hover {background: #DCDDE1;color: black}       .rectangle a:before {content: counter(li);counter-increment: li;position: absolute;left: -2.5em;top: 50%;margin-top: -1em;background: #9097A2;height: 2em;width: 2em;line-height: 2em;text-align: center;font-weight: bold;}.rectangle a:after {position: absolute;content: "";border: .5em solid transparent;left: -1em;top: 50%;margin-top: -.5em;transition: all .3s ease-out;}.rectangle a:hover:after {left: -.5em;border-left-color: #9097A2;}a:hover{cursor: pointer}.rectangle-item.active {background-color: #27203a !important;border: white 1px solid;padding-left: 15px;}.rectangle-item.active a:hover {background: none;color: #fff}#currenttitle {display: block !important;font: 700 20pt sans-serif;color: #FFFFFF;text-align: center !important;}@media (min-width: 1015px){#videowrap{width: 70vw}}@media (max-width: 1015px){#leftpanel{background-color:black;position: fixed !important;bottom:0px;margin-right: 0px;left: 0px;top: 50px; height: calc(100vh - 50px) !important;width: 100vw}a.navbar-brand {padding: 15px 50px;}#chat-btn{position: fixed;top: 0px;padding-top: 15px;left: -5px;padding-right: 15px;padding-left: 23px;height: 50px;}}@media (min-width: 1015px){#chat-btn{display: none}#leftpanel{display: block !mportant}.rectangle{display:none}#sl-btn{display: block !important;position: fixed;top: 8px;right:15px;z-index: 9999 !important}#currenttitle{padding-top: 5px;background: #27203a;}}</style>`).appendTo('body');$('<button id="sl-btn" class="btn btn-sm btn-default"><i class="glyphicon glyphicon-menu-hamburger"></button>').insertAfter('#videowrap').on("click",function(){if(!$(this).hasClass('btn-success')){$(this).addClass('btn-success');$('<style class="sl-show">').appendTo('body').text('.rectangle{display:block !important;background: rgba(0, 0, 0, 0.85);position: fixed;width: 70vw;top: 50px;height: calc(100vh - 50px);max-height: calc(100vh - 50px);overflow-y: auto;}')}else{$(this).removeClass('btn-success');$('.sl-show').remove();}});
//Default player
$('ol > li:nth-child(2)').click();